---
kind: Pod
apiVersion: v1

metadata:
  name: mydb-pod
  namespace: myns
  labels:
    name: mydb-pod
    version: "v1"

spec:
  containers:
  - name: mydb-container 
    image: stackupiss/northwind-db:v1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3306