---
kind: ConfigMap
apiVersion: v1
metadata:
    name: weather-config
    namespace: myns
    labels:
        app: weather-config

data:
    db_host: mydb-svc.myns.svc.cluster.local

---
kind: Secret
apiVersion: v1
metadata:
    name: weather-secret
    namespace: myns
    labels:
        app: weather-secret

data:
    db_password: Y2hhbmdlaXQ=

---
kind: Deployment
apiVersion: apps/v1

metadata:
    name: weather-deploy
    namespace: myns
    labels:
        app: weather-deploy

spec:
    replicas: 1
    selector:
        matchLabels:
            app: weather-pod
    template:
        metadata:
            name: weather-pod
            labels:
                app: weather-pod
                version: v1
        spec:
            containers:
            - name: weather
              image: stackupiss/weather:v1
              imagePullPolicy: Always
              resources:
                requests:
                    cpu: 100m
                limits:
                    cpu: 100m    
              env:
              - name: APP_ID
                value: b60dc24f17824b5a7680430157e925f1
              - name: APP_DEFAULT_CITY
                value: SINGAPORE
              ports:
              - name: weather-port
                containerPort: 3000

---
kind: Service
apiVersion: v1

metadata:
    name: weather-svc
    namespace: myns
    labels:
        app: weather-svc

spec:
    type: LoadBalancer
    selector:
        app: weather-pod
    ports:
    - name: weather-svc-port
      port: 80
      targetPort: weather-port